Mix to Vite migration
laravel/telescope pull request #1391
Opened 2023-10-14 10:06 UTC by esurov

Migrated from laravel mix to vite following official migration guide: https://laravel.com/docs/10.x/vite

vite

2023-10-18 22:25 UTC, crynobone requested changes

2023-10-18 22:25 UTC, crynobone commented on resources/js/app.js
> +import copyClipboard from './components/CopyClipboard.vue';
```suggestion
import RelatedEntries from './components/RelatedEntries.vue';
import IndexScreen from './components/IndexScreen.vue';
import PreviewScreen from './components/PreviewScreen.vue';
import AlertComponent from './components/Alert.vue';
import CopyClipboard from './components/CopyClipboard.vue';
```

2023-10-18 22:25 UTC, crynobone commented on resources/js/app.js
> +Vue.component('copy-clipboard', copyClipboard);
```suggestion
Vue.component('related-entries', RelatedEntries);
Vue.component('index-screen', IndexScreen);
Vue.component('preview-screen', PreviewScreen);
Vue.component('alert', AlertComponent);
Vue.component('copy-clipboard', CopyClipboard);
```

2023-10-18 22:26 UTC, crynobone commented on resources/js/routes.js
> +import clientRequestsIndex from './screens/client-requests/index.vue';
Should follow same `studly` case

2023-10-18 22:27 UTC, crynobone commented on resources/js/screens/logs/preview.vue
> +    import stacktrace from "../../components/Stacktrace.vue";
```suggestion
    import exceptionCodePreview from "@/components/ExceptionCodePreview.vue";
    import stacktrace from "@/components/Stacktrace.vue";
```

2023-10-18 22:27 UTC, crynobone commented on resources/js/screens/logs/preview.vue
> +            'stack-trace': stacktrace
```suggestion
            'code-preview': ExceptionCodePreview,
            'stack-trace': Stacktrace
```

2023-10-18 22:28 UTC, crynobone commented on resources/js/screens/jobs/preview.vue
> +    import stacktrace from "../../components/Stacktrace.vue";
```suggestion
    import exceptionCodePreview from "@/components/ExceptionCodePreview.vue";
    import stacktrace from "@/components/Stacktrace.vue";
```

2023-10-18 22:28 UTC, crynobone commented on resources/js/screens/jobs/preview.vue
> +            'stack-trace': stacktrace
```suggestion
            'code-preview': ExceptionCodePreview,
            'stack-trace': Stacktrace
```

2023-10-18 22:29 UTC, crynobone commented on resources/js/screens/exceptions/preview.vue
> +    import stacktrace from "../../components/Stacktrace.vue";
```suggestion
    import exceptionCodePreview from "@/components/ExceptionCodePreview.vue";
    import stacktrace from "@/components/Stacktrace.vue";
```

2023-10-18 22:29 UTC, crynobone commented on resources/js/screens/exceptions/preview.vue
> +            'stack-trace': stacktrace
```suggestion
            'code-preview': ExceptionCodePreview,
            'stack-trace': Stacktrace
```

2023-10-19 06:43 UTC, esurov commented on resources/js/routes.js
> +import clientRequestsIndex from './screens/client-requests/index.vue';
Fixed

2023-10-19 07:09 UTC, crynobone approved these changes

2023-10-26 14:27 UTC, merged

2023-11-01 10:54 UTC, francoism90 commented
Hmm, I'm keep getting the following error after upgrading:
```
GET http://localhost:5173/resources/sass/app.scss net::ERR_ABORTED 404 (Not Found)
```
I've run `npm run build` and use Vite.

Horizon, etc. work fine, but Telescope is broken.

2023-11-01 13:59 UTC, taylorotwell commented
@esurov Telescope actually doesn't even work in Laravel applications anymore?

2023-11-01 13:59 UTC, taylorotwell commented
https://github.com/laravel/telescope/issues/1399

2023-11-01 15:06 UTC, wfern commented
@esurov the problem is the "hot file" path...

It need to be set in place or before of the @vite directive or called somewhere before rendering.

The problem is because the default hot path is relative to the main application not telescope, so when we run `npm run dev` it gets the hot file from the main application: https://github.com/laravel/framework/blob/d0a6080db78a7e8a3316ff9c41eb86aa0866742d/src/Illuminate/Foundation/Vite.php#L170C54-L170C54

Example how to fix:
```php
// .../telescope/resources/view/layout.blade.php

// Maybe it's better to set it in the TelescopeServiceProvider but this works for test purposes 
{{ Vite::useHotFile('public/hot') }}
    
@vite('resources/sass/' . $cssFile, '/vendor/telescope/build')```

2023-11-12 23:26 UTC, timacdonald commented
If we revisit this, we should consider: https://github.com/laravel/framework/issues/48964

2023-11-17 08:37 UTC, daniser commented
As a person who extensively uses Vite in my own packages, I already have solutions for this problem.

### Define hot file path in template

_layout.blade.php_
```blade
{{ Vite::useHotFile('vendor/my-package/hot')
    ->useBuildDirectory('vendor/my-package/build')
    ->withEntryPoints(['resources/js/app.js', "resources/js/pages/{$page['component']}.vue"]) }}
```
The problem with this solution is, the `Vite` class is singleton, so it may affect main app entry points/build dir/hot file path etc in unpredictable ways.

### Use macro or mixin

_MyPackageServiceProvider.php_
```php
public function boot()
{
    Vite::mixin(new Support\ViteAliasMixin);
}
```
_ViteAliasMixin.php_
```php
<?php

namespace MyVendor\MyPackage\Support;

use Illuminate\Foundation\Vite;

class ViteAliasMixin
{
    protected function myPackageEntryPoint(): \Closure
    {
        return fn (array $page) => $this
            ->useHotFile('vendor/my-package/hot')
            ->useBuildDirectory('vendor/my-package/build')
            ->withEntryPoints(['resources/js/app.js', "resources/js/pages/{$page['component']}.vue"]);
    }
}
```
_layout.blade.php_
```blade
{{ Vite::myPackageEntryPoint($page) }}
```
I use this solution in my packages, but it has same flaws as the previous one.

### Implement some kind of Vite config manager and configure its instance in package's service provider
I already [had PR for this](https://github.com/laravel/framework/pull/45257), but unfortunately it was closed, so I implemented this functionality [as a package](https://github.com/ttbooking/vite-manager).
I use this in my project, but not in my packages yet, as I don't want excess dependencies. I hope maybe one day we'll revisit this PR and it'll made its way into core?

_MyPackageServiceProvider.php_
```php
public function boot()
{
    Vite::app('myapp')
        ->useHotFile('vendor/my-package/hot')
        ->useBuildDirectory('vendor/my-package/build')
        ->withEntryPoints(['resources/js/app.js']);
}
```
_layout.blade.php_
```blade
@viteApp('myapp')
```