[5.x] Encrypt content attribute at rest
laravel/telescope pull request #1533
Opened 2024-10-04 19:36 UTC by gawsoftpl

Pull request for #1532 [Feature] Encryption at the Rest

2024-10-05 00:35 UTC, crynobone commented
Marking this as draft since tests are failing

2024-10-06 01:51 UTC, crynobone requested changes

2024-10-06 01:51 UTC, crynobone commented on src/Storage/EntryModelEncryptionCast.php
> +        return config('telescope.encryption');
On existing application with published config this would return `null`.

2024-10-06 21:10 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

2024-10-06 21:10 UTC, closed without merging

2024-10-07 16:37 UTC, gawsoftpl commented
I can create new package. Best way will be use ModelObserver but I dont know why ModelOberser not working with [EntryModel.php](https://github.com/laravel/telescope/blob/5.x/src/Storage/EntryModel.php)

Not fired `creating` hook, retrieved working fine.

2024-10-07 16:37 UTC, gawsoftpl commented
> Thanks for your pull request to Laravel!
> 
> Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include.
> 
> If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

I can create new package. Best way will be use ModelObserver but I dont know why ModelOberser not working with [EntryModel.php](https://github.com/laravel/telescope/blob/5.x/src/Storage/EntryModel.php)

Not fired `creating` hook, retrieved working fine.